name: Deploy Hugo site via gh-pages

on:
  push:
    branches:
      - master # Il tuo branch principale

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Scarica il tema
          fetch-depth: 0        # Scarica la storia per GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Azione per installare Hugo
        with:
          hugo-version: '0.141.0' # Versione di Hugo
          extended: true # Versione Extended
          install-dart-sass: true # Installa Dart Sass automaticamente

      # I passi per Node.js e 'npm install -g sass' sono stati RIMOSSI

      - name: Build Sito
        run: hugo --minify # Un solo passo di build è sufficiente

      - name: Deploy su branch gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token automatico
          publish_dir: ./public # Cartella da pubblicare
          # Puoi decommentare (togliere #) e modificare le righe seguenti se vuoi personalizzare il commit sul branch gh-pages
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: ${{ github.event.head_commit.message }}