name: Deploy Hugo site via gh-pages

on:
  push:
    branches:
      - master # Il tuo branch principale
  workflow_dispatch:

# Permessi necessari per l'azione actions-gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Scarica il tema
          fetch-depth: 0        # Scarica la storia per GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Azione per installare Hugo
        with:
          hugo-version: '0.141.0' # Versione di Hugo
          extended: true # Versione Extended
          # La riga 'install-dart-sass: true' è stata rimossa perché non valida qui

      # Passi per installare Dart Sass direttamente
      - name: Install Dart Sass
        run: |
          SASS_VERSION=1.77.8 # Versione specifica di Dart Sass
          wget -O dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/${SASS_VERSION}/dart-sass-${SASS_VERSION}-linux-x64.tar.gz
          tar -xf dart-sass.tar.gz
          rm dart-sass.tar.gz
          echo "${PWD}/dart-sass" >> $GITHUB_PATH # Aggiunge sass al PATH

      # Un solo passo di Build
      - name: Build Sito
        run: hugo --minify 

      # Passo per il Deploy sul branch gh-pages
      - name: Deploy su branch gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Usa il token di GitHub Actions
          publish_dir: ./public # Cartella da pubblicare
          # Le righe seguenti sono opzionali
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: ${{ github.event.head_commit.message }}