name: Deploy Hugo site via gh-pages

on:
  push:
    branches:
      - master # Il tuo branch principale

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Scarica il tema
          fetch-depth: 0        # Scarica la storia per GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Azione per installare Hugo
        with:
          hugo-version: '0.119.0' # Versione di Hugo (puoi cambiarla se serve)
          extended: true # Versione Extended necessaria per il tema Paige

      - name: Build Sito
        run: hugo --minify # Costruisce il sito nella cartella /public

      - name: Deploy su branch gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token automatico per permettere il push
          publish_dir: ./public # Cartella da pubblicare
          # publish_branch: gh-pages # Nome del branch di destinazione (default)
          # user_name: 'github-actions[bot]' # Nome commit (opzionale)
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Email commit (opzionale)
          # commit_message: ${{ github.event.head_commit.message }} # Messaggio commit (opzionale)